#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Boxen doesn't play terribly well with others (i.e. setting HOMEBREW_CASK_OPTS), so run it first
[ -f /opt/boxen/env.sh ] && source /opt/boxen/env.sh

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Python shell init script
export PYTHONSTARTUP="$HOME/.pythonstartup"

# Travis completion
[ -f $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh

# Set up GVM
[[ -s "$HOME/.gvm/bin/gvm-init.sh" ]] && source "$HOME/.gvm/bin/gvm-init.sh"

function update_spacemacs() {
     pushd $HOME/.emacs.d
     git pull --rebase
     git submodule sync; git submodule update
     popd
}

function gradle() {
	# http://unix.stackexchange.com/questions/13464/is-there-a-way-to-find-a-file-in-an-inverse-recursive-search
	function upsearch() {
		test / = "$PWD" && return || test -e "$1" && echo "$PWD/$1" && return || cd .. && upsearch "$1"
	}

	local gradlew="$(upsearch gradlew)"
	if [ -z "$gradlew" ]; then
		command gradle "$@"
	else
		"$gradlew" "$@"
	fi
}

# Workaround for Boxen's Cask environment script
export HOMEBREW_CASK_OPTS="$MY_HOMEBREW_CASK_OPTS $HOMEBREW_CASK_OPTS"

if brew command command-not-found-init > /dev/null; then eval "$(brew command-not-found-init)"; fi

test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh
