#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Python shell init script
export PYTHONSTARTUP="$HOME/.pythonstartup"

# Travis completion
[-f $HOME/.travis/travis.sh ] && source $HOME/.travis/travis.sh
